package com.zhadko.mapsapp.utils

object Const {

    const val ACTION_START_LOCATION_TRACK = "ACTION_START_LOCATION_TRACK"
    const val ACTION_STOP_LOCATION_TRACK = "ACTION_STOP_LOCATION_TRACK"

    const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME = "NOTIFICATION_CHANNEL_NAME"
    const val NOTIFICATION_ID = 3

    const val PENDING_INTENT_REQUEST_CODE = 99
}